### ISSUE TITLE
Are you abandoning this project?

### ISSUE THREAD

**Issue by cmosguy** [alexandresalome/mailcatcher#13]
@alexandresalome this is an awesome tool, but I was just wondering if you were abandoning this project?  Reason why I am asking is it would be great to use this with Behat 3.  Any chances of this happening?

Cheers!

**Comment by alexandresalome** [comment]
I merged #9, sorry sometimes I'm far away from Github :) Sorry for the inconvenience ;)

**Comment by akovalyov** [comment]
@alexandresalome could you also tag a new release please?
