### ISSUE TITLE
Mail parser doesn't work with Content-Type: multipart/related; 	type="text/html"; 	boundary="

### ISSUE THREAD

**Issue by nirbhaypatil** [alexandresalome/mailcatcher#26]
Unable to parse header with content type 
``
Content-Type: multipart/related;
	type="text/html";
	boundary="b1_e8edc21b734355033c4c1981d9786e10"
``

Current regex in loadParts from  Alex\MailCatcher\Mime\Part doesn't handle this.
It throws error.
 Unable to parse multipart header: "multipart/related;type="text/html"; (InvalidArgumentException)

**Comment by alexandresalome** [comment]
Resolved by #27
