### ISSUE TITLE
Mail parser doesn't work with alternative/mixed multipart mail

### ISSUE THREAD

**Issue by matthiasnoback** [alexandresalome/mailcatcher#7]
I had an email (created with SwiftMailer) with only HTML text and a PDF attachment. This library couldn't parse the mail. Then I tried having a text/plain body and an alternative text/html body and finally the PDF attachment.

Both these scenario's didn't work - the problem occurs at line 112 of `Part.php`.

Do you have an alternative? It seems the mail parser part of this library is just not generic enough to handle all kinds of mail types (including the not particularly exotic type of mail I'm using here). Maybe there is a stand-alone mail parser which could be used as a dependency of this library (I didn't look into this yet, but I will).

**Comment by alexandresalome** [comment]
I tried to reproduce the issue with a mail of the same type (only HTML + PDF attachment), but got no issue parsing it.

Have you kept the e-mail?

**Comment by alexandresalome** [comment]
Actually, it's fixed by #3

**Comment by matthiasnoback** [comment]
Thanks, if I ever feel the need to test emails again, I'll reach back to this tool :)
